### ISSUE TITLE
stm32f103_usart1 does not build with gcc 5.4.1

### ISSUE THREAD

**Issue by elsni** [spacerace/HY-MiniSTM32V#1]
Linking fails with error:
section .init loaded at [08005f0c,08005f0f] overlaps section .data loaded at [08005f0c,080068c7]

Linking also failed before when directory "output" is not present. which is not in the repository.

**Comment by spacerace** [comment]
It seems there is a problem with the linker script. I will have a look 
at it soon.


Thanks for your mail on this topic.


Nils
